/**
 * Function registry — auto-generated by `npm run update` (scripts/update.ts).
 * Do not edit by hand. Mirrors VueUse's generated
 * `packages/metadata/metadata.ts` (react-adapted).
 */
export interface FunctionInfo {
  name: string
  pkg: string
  file: string
}

export const functions: FunctionInfo[] = [
  {
    name: 'assert',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'clamp',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'createSingletonPromise',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'customStorageEventName',
    file: 'packages/core/src/useStorage.ts',
    pkg: 'core',
  },
  {
    name: 'debounceFilter',
    file: 'packages/shared/src/useWatchWithFilter.ts',
    pkg: 'shared',
  },
  {
    name: 'formatDate',
    file: 'packages/shared/src/useDateFormat.ts',
    pkg: 'shared',
  },
  {
    name: 'formatTimeAgo',
    file: 'packages/core/src/useTimeAgo.ts',
    pkg: 'core',
  },
  {
    name: 'formatTimeAgoIntl',
    file: 'packages/core/src/useTimeAgoIntl.ts',
    pkg: 'core',
  },
  {
    name: 'formatTimeAgoIntlParts',
    file: 'packages/core/src/useTimeAgoIntl.ts',
    pkg: 'core',
  },
  {
    name: 'guessSerializerType',
    file: 'packages/core/src/useStorage.ts',
    pkg: 'core',
  },
  {
    name: 'hasOwn',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'hyphenate',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'increaseWithUnit',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'increaseWithUnit',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'increaseWithUnit',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'increaseWithUnit',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'isClient',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'isDef',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'isIOS',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'isObject',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'isRefLike',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'noop',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'normalizeDate',
    file: 'packages/shared/src/useDateFormat.ts',
    pkg: 'shared',
  },
  {
    name: 'now',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'objectOmit',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'objectPick',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'promiseTimeout',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'rand',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'throttleFilter',
    file: 'packages/shared/src/useWatchWithFilter.ts',
    pkg: 'shared',
  },
  {
    name: 'timestamp',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'toArray',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'toArray',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'toArray',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'toValue',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'toValue',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'toValue',
    file: 'packages/shared/src/utils.ts',
    pkg: 'shared',
  },
  {
    name: 'TransitionPresets',
    file: 'packages/core/src/useTransition.ts',
    pkg: 'core',
  },
  {
    name: 'useArrayDifference',
    file: 'packages/shared/src/useArrayDifference.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayDifference',
    file: 'packages/shared/src/useArrayDifference.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayDifference',
    file: 'packages/shared/src/useArrayDifference.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayEvery',
    file: 'packages/shared/src/useArrayEvery.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayFilter',
    file: 'packages/shared/src/useArrayFilter.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayFilter',
    file: 'packages/shared/src/useArrayFilter.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayFilter',
    file: 'packages/shared/src/useArrayFilter.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayFind',
    file: 'packages/shared/src/useArrayFind.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayFindIndex',
    file: 'packages/shared/src/useArrayFindIndex.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayFindLast',
    file: 'packages/shared/src/useArrayFindLast.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayIncludes',
    file: 'packages/shared/src/useArrayIncludes.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayIncludes',
    file: 'packages/shared/src/useArrayIncludes.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayIncludes',
    file: 'packages/shared/src/useArrayIncludes.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayIncludes',
    file: 'packages/shared/src/useArrayIncludes.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayJoin',
    file: 'packages/shared/src/useArrayJoin.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayMap',
    file: 'packages/shared/src/useArrayMap.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayReduce',
    file: 'packages/shared/src/useArrayReduce.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayReduce',
    file: 'packages/shared/src/useArrayReduce.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayReduce',
    file: 'packages/shared/src/useArrayReduce.ts',
    pkg: 'shared',
  },
  {
    name: 'useArraySome',
    file: 'packages/shared/src/useArraySome.ts',
    pkg: 'shared',
  },
  {
    name: 'useArrayUnique',
    file: 'packages/shared/src/useArrayUnique.ts',
    pkg: 'shared',
  },
  {
    name: 'useCounter',
    file: 'packages/shared/src/useCounter.ts',
    pkg: 'shared',
  },
  {
    name: 'useDateFormat',
    file: 'packages/shared/src/useDateFormat.ts',
    pkg: 'shared',
  },
  {
    name: 'useDebounceFn',
    file: 'packages/shared/src/useDebounceFn.ts',
    pkg: 'shared',
  },
  {
    name: 'useInterval',
    file: 'packages/shared/src/useInterval.ts',
    pkg: 'shared',
  },
  {
    name: 'useInterval',
    file: 'packages/shared/src/useInterval.ts',
    pkg: 'shared',
  },
  {
    name: 'useInterval',
    file: 'packages/shared/src/useInterval.ts',
    pkg: 'shared',
  },
  {
    name: 'useIntervalFn',
    file: 'packages/shared/src/useIntervalFn.ts',
    pkg: 'shared',
  },
  {
    name: 'useLastChanged',
    file: 'packages/shared/src/useLastChanged.ts',
    pkg: 'shared',
  },
  {
    name: 'useLastChanged',
    file: 'packages/shared/src/useLastChanged.ts',
    pkg: 'shared',
  },
  {
    name: 'useLastChanged',
    file: 'packages/shared/src/useLastChanged.ts',
    pkg: 'shared',
  },
  {
    name: 'useMount',
    file: 'packages/shared/src/useMount.ts',
    pkg: 'shared',
  },
  {
    name: 'useMounted',
    file: 'packages/core/src/useMounted.ts',
    pkg: 'core',
  },
  {
    name: 'useNow',
    file: 'packages/core/src/useNow.ts',
    pkg: 'core',
  },
  {
    name: 'useOnline',
    file: 'packages/core/src/useOnline.ts',
    pkg: 'core',
  },
  {
    name: 'useParentElement',
    file: 'packages/core/src/useParentElement.ts',
    pkg: 'core',
  },
  {
    name: 'usePerformanceObserver',
    file: 'packages/core/src/usePerformanceObserver.ts',
    pkg: 'core',
  },
  {
    name: 'usePermission',
    file: 'packages/core/src/usePermission.ts',
    pkg: 'core',
  },
  {
    name: 'usePermission',
    file: 'packages/core/src/usePermission.ts',
    pkg: 'core',
  },
  {
    name: 'usePermission',
    file: 'packages/core/src/usePermission.ts',
    pkg: 'core',
  },
  {
    name: 'usePointer',
    file: 'packages/core/src/usePointer.ts',
    pkg: 'core',
  },
  {
    name: 'usePointerLock',
    file: 'packages/core/src/usePointerLock.ts',
    pkg: 'core',
  },
  {
    name: 'usePointerSwipe',
    file: 'packages/core/src/usePointerSwipe.ts',
    pkg: 'core',
  },
  {
    name: 'usePreferredColorScheme',
    file: 'packages/core/src/usePreferredColorScheme.ts',
    pkg: 'core',
  },
  {
    name: 'usePreferredContrast',
    file: 'packages/core/src/usePreferredContrast.ts',
    pkg: 'core',
  },
  {
    name: 'usePreferredDark',
    file: 'packages/core/src/usePreferredDark.ts',
    pkg: 'core',
  },
  {
    name: 'usePreferredLanguages',
    file: 'packages/core/src/usePreferredLanguages.ts',
    pkg: 'core',
  },
  {
    name: 'usePreferredReducedMotion',
    file: 'packages/core/src/usePreferredReducedMotion.ts',
    pkg: 'core',
  },
  {
    name: 'usePreferredReducedTransparency',
    file: 'packages/core/src/usePreferredReducedTransparency.ts',
    pkg: 'core',
  },
  {
    name: 'usePrevious',
    file: 'packages/core/src/usePrevious.ts',
    pkg: 'core',
  },
  {
    name: 'useResizeObserver',
    file: 'packages/core/src/useResizeObserver.ts',
    pkg: 'core',
  },
  {
    name: 'useScreenOrientation',
    file: 'packages/core/src/useScreenOrientation.ts',
    pkg: 'core',
  },
  {
    name: 'useScreenSafeArea',
    file: 'packages/core/src/useScreenSafeArea.ts',
    pkg: 'core',
  },
  {
    name: 'useScriptTag',
    file: 'packages/core/src/useScriptTag.ts',
    pkg: 'core',
  },
  {
    name: 'useScroll',
    file: 'packages/core/src/useScroll.ts',
    pkg: 'core',
  },
  {
    name: 'useScrollLock',
    file: 'packages/core/src/useScrollLock.ts',
    pkg: 'core',
  },
  {
    name: 'useSessionStorage',
    file: 'packages/core/src/useSessionStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useSessionStorage',
    file: 'packages/core/src/useSessionStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useSessionStorage',
    file: 'packages/core/src/useSessionStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useSessionStorage',
    file: 'packages/core/src/useSessionStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useSessionStorage',
    file: 'packages/core/src/useSessionStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useSessionStorage',
    file: 'packages/core/src/useSessionStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useShare',
    file: 'packages/core/src/useShare.ts',
    pkg: 'core',
  },
  {
    name: 'useSorted',
    file: 'packages/core/src/useSorted.ts',
    pkg: 'core',
  },
  {
    name: 'useSpeechRecognition',
    file: 'packages/core/src/useSpeechRecognition.ts',
    pkg: 'core',
  },
  {
    name: 'useSpeechSynthesis',
    file: 'packages/core/src/useSpeechSynthesis.ts',
    pkg: 'core',
  },
  {
    name: 'useStateHistory',
    file: 'packages/core/src/useStateHistory.ts',
    pkg: 'core',
  },
  {
    name: 'useStateManualHistory',
    file: 'packages/core/src/useStateManualHistory.ts',
    pkg: 'core',
  },
  {
    name: 'useStateThrottledHistory',
    file: 'packages/core/src/useStateThrottledHistory.ts',
    pkg: 'core',
  },
  {
    name: 'useStepper',
    file: 'packages/core/src/useStepper.ts',
    pkg: 'core',
  },
  {
    name: 'useStorage',
    file: 'packages/core/src/useStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useStorage',
    file: 'packages/core/src/useStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useStorage',
    file: 'packages/core/src/useStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useStorage',
    file: 'packages/core/src/useStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useStorage',
    file: 'packages/core/src/useStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useStorage',
    file: 'packages/core/src/useStorage.ts',
    pkg: 'core',
  },
  {
    name: 'useStorageAsync',
    file: 'packages/core/src/useStorageAsync.ts',
    pkg: 'core',
  },
  {
    name: 'useStorageAsync',
    file: 'packages/core/src/useStorageAsync.ts',
    pkg: 'core',
  },
  {
    name: 'useStorageAsync',
    file: 'packages/core/src/useStorageAsync.ts',
    pkg: 'core',
  },
  {
    name: 'useStorageAsync',
    file: 'packages/core/src/useStorageAsync.ts',
    pkg: 'core',
  },
  {
    name: 'useStorageAsync',
    file: 'packages/core/src/useStorageAsync.ts',
    pkg: 'core',
  },
  {
    name: 'useStorageAsync',
    file: 'packages/core/src/useStorageAsync.ts',
    pkg: 'core',
  },
  {
    name: 'useStyleTag',
    file: 'packages/core/src/useStyleTag.ts',
    pkg: 'core',
  },
  {
    name: 'useSupported',
    file: 'packages/core/src/useSupported.ts',
    pkg: 'core',
  },
  {
    name: 'useSwipe',
    file: 'packages/core/src/useSwipe.ts',
    pkg: 'core',
  },
  {
    name: 'useTemporalNow',
    file: 'packages/core/src/useTemporalNow.ts',
    pkg: 'core',
  },
  {
    name: 'useTextareaAutosize',
    file: 'packages/core/src/useTextareaAutosize.ts',
    pkg: 'core',
  },
  {
    name: 'useTextDirection',
    file: 'packages/core/src/useTextDirection.ts',
    pkg: 'core',
  },
  {
    name: 'useTextSelection',
    file: 'packages/core/src/useTextSelection.ts',
    pkg: 'core',
  },
  {
    name: 'useThrottleFn',
    file: 'packages/shared/src/useThrottleFn.ts',
    pkg: 'shared',
  },
  {
    name: 'useTimeAgo',
    file: 'packages/core/src/useTimeAgo.ts',
    pkg: 'core',
  },
  {
    name: 'useTimeAgoIntl',
    file: 'packages/core/src/useTimeAgoIntl.ts',
    pkg: 'core',
  },
  {
    name: 'useTimeout',
    file: 'packages/shared/src/useTimeout.ts',
    pkg: 'shared',
  },
  {
    name: 'useTimeout',
    file: 'packages/shared/src/useTimeout.ts',
    pkg: 'shared',
  },
  {
    name: 'useTimeout',
    file: 'packages/shared/src/useTimeout.ts',
    pkg: 'shared',
  },
  {
    name: 'useTimeoutFn',
    file: 'packages/shared/src/useTimeoutFn.ts',
    pkg: 'shared',
  },
  {
    name: 'useTimeoutPoll',
    file: 'packages/core/src/useTimeoutPoll.ts',
    pkg: 'core',
  },
  {
    name: 'useTimestamp',
    file: 'packages/core/src/useTimestamp.ts',
    pkg: 'core',
  },
  {
    name: 'useTimestamp',
    file: 'packages/core/src/useTimestamp.ts',
    pkg: 'core',
  },
  {
    name: 'useTimestamp',
    file: 'packages/core/src/useTimestamp.ts',
    pkg: 'core',
  },
  {
    name: 'useTitle',
    file: 'packages/core/src/useTitle.ts',
    pkg: 'core',
  },
  {
    name: 'useToggle',
    file: 'packages/shared/src/useToggle.ts',
    pkg: 'shared',
  },
  {
    name: 'useToNumber',
    file: 'packages/shared/src/useToNumber.ts',
    pkg: 'shared',
  },
  {
    name: 'useToString',
    file: 'packages/shared/src/useToString.ts',
    pkg: 'shared',
  },
  {
    name: 'useTransition',
    file: 'packages/core/src/useTransition.ts',
    pkg: 'core',
  },
  {
    name: 'useTransition',
    file: 'packages/core/src/useTransition.ts',
    pkg: 'core',
  },
  {
    name: 'useTransition',
    file: 'packages/core/src/useTransition.ts',
    pkg: 'core',
  },
  {
    name: 'useUnmount',
    file: 'packages/shared/src/useUnmount.ts',
    pkg: 'shared',
  },
  {
    name: 'useUpdate',
    file: 'packages/shared/src/useUpdate.ts',
    pkg: 'shared',
  },
  {
    name: 'useUrlSearchParams',
    file: 'packages/core/src/useUrlSearchParams.ts',
    pkg: 'core',
  },
  {
    name: 'useUserMedia',
    file: 'packages/core/src/useUserMedia.ts',
    pkg: 'core',
  },
  {
    name: 'useVibrate',
    file: 'packages/core/src/useVibrate.ts',
    pkg: 'core',
  },
  {
    name: 'useWakeLock',
    file: 'packages/core/src/useWakeLock.ts',
    pkg: 'core',
  },
  {
    name: 'useWatch',
    file: 'packages/shared/src/useWatch.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatch',
    file: 'packages/shared/src/useWatch.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatch',
    file: 'packages/shared/src/useWatch.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchArray',
    file: 'packages/shared/src/useWatchArray.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchAtMost',
    file: 'packages/shared/src/useWatchAtMost.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchAtMost',
    file: 'packages/shared/src/useWatchAtMost.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchAtMost',
    file: 'packages/shared/src/useWatchAtMost.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchDebounced',
    file: 'packages/shared/src/useWatchDebounced.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchDebounced',
    file: 'packages/shared/src/useWatchDebounced.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchDebounced',
    file: 'packages/shared/src/useWatchDebounced.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchDeep',
    file: 'packages/shared/src/useWatchDeep.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchDeep',
    file: 'packages/shared/src/useWatchDeep.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchDeep',
    file: 'packages/shared/src/useWatchDeep.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchIgnorable',
    file: 'packages/shared/src/useWatchIgnorable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchIgnorable',
    file: 'packages/shared/src/useWatchIgnorable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchIgnorable',
    file: 'packages/shared/src/useWatchIgnorable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchImmediate',
    file: 'packages/shared/src/useWatchImmediate.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchImmediate',
    file: 'packages/shared/src/useWatchImmediate.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchImmediate',
    file: 'packages/shared/src/useWatchImmediate.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchOnce',
    file: 'packages/shared/src/useWatchOnce.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchOnce',
    file: 'packages/shared/src/useWatchOnce.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchOnce',
    file: 'packages/shared/src/useWatchOnce.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchPausable',
    file: 'packages/shared/src/useWatchPausable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchPausable',
    file: 'packages/shared/src/useWatchPausable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchPausable',
    file: 'packages/shared/src/useWatchPausable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchThrottled',
    file: 'packages/shared/src/useWatchThrottled.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchThrottled',
    file: 'packages/shared/src/useWatchThrottled.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchThrottled',
    file: 'packages/shared/src/useWatchThrottled.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchTriggerable',
    file: 'packages/shared/src/useWatchTriggerable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchTriggerable',
    file: 'packages/shared/src/useWatchTriggerable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchTriggerable',
    file: 'packages/shared/src/useWatchTriggerable.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchWithFilter',
    file: 'packages/shared/src/useWatchWithFilter.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchWithFilter',
    file: 'packages/shared/src/useWatchWithFilter.ts',
    pkg: 'shared',
  },
  {
    name: 'useWatchWithFilter',
    file: 'packages/shared/src/useWatchWithFilter.ts',
    pkg: 'shared',
  },
  {
    name: 'useWebNotification',
    file: 'packages/core/src/useWebNotification.ts',
    pkg: 'core',
  },
  {
    name: 'useWebWorker',
    file: 'packages/core/src/useWebWorker.ts',
    pkg: 'core',
  },
  {
    name: 'useWebWorker',
    file: 'packages/core/src/useWebWorker.ts',
    pkg: 'core',
  },
  {
    name: 'useWebWorker',
    file: 'packages/core/src/useWebWorker.ts',
    pkg: 'core',
  },
  {
    name: 'useWhenever',
    file: 'packages/shared/src/useWhenever.ts',
    pkg: 'shared',
  },
  {
    name: 'useWindowFocus',
    file: 'packages/core/src/useWindowFocus.ts',
    pkg: 'core',
  },
  {
    name: 'useWindowScroll',
    file: 'packages/core/src/useWindowScroll.ts',
    pkg: 'core',
  },
  {
    name: 'useWindowSize',
    file: 'packages/core/src/useWindowSize.ts',
    pkg: 'core',
  },
]
