/**
 * Function registry — auto-generated by `npm run update` (scripts/update.ts).
 * Do not edit by hand. Mirrors VueUse's generated
 * `packages/metadata/metadata.ts` (react-adapted).
 */
export interface FunctionInfo {
  name: string
  pkg: string
  file: string
}

export const functions: FunctionInfo[] = [
  {
    name: 'useCounter',
    file: 'packages/shared/src/useCounter.ts',
    pkg: 'shared',
  },
  {
    name: 'useMount',
    file: 'packages/shared/src/useMount.ts',
    pkg: 'shared',
  },
  {
    name: 'useNow',
    file: 'packages/core/src/useNow.ts',
    pkg: 'core',
  },
  {
    name: 'useToggle',
    file: 'packages/shared/src/useToggle.ts',
    pkg: 'shared',
  },
  {
    name: 'useUnmount',
    file: 'packages/shared/src/useUnmount.ts',
    pkg: 'shared',
  },
  {
    name: 'useUpdate',
    file: 'packages/shared/src/useUpdate.ts',
    pkg: 'shared',
  },
]
