/**
 * @reaxuse/metadata — React port of @vueuse/metadata
 *
 * Exposes the package manifests that drive the docs site and the
 * mapping progress table (meta/functions.md, regenerated by
 * `npm run update`).
 */
export type { PackageManifest } from '../../../meta/packages'
export { packages } from '../../../meta/packages'
