/**
 * @reaxuse/metadata — React port of @vueuse/metadata
 *
 * Exposes the package manifests and the function registry that drive
 * the docs site, the mapping progress table (meta/functions.md) and
 * the markdown auto-linking plugin. The registry (`./functions`) is
 * regenerated by `npm run update` (scripts/update.ts), mirroring
 * VueUse's generated `packages/metadata/metadata.ts`.
 */
export type { PackageManifest } from '../../../meta/packages'
export { packages } from '../../../meta/packages'
export type { FunctionInfo } from './functions'
export { functions } from './functions'
