import type { PackageManifest } from '../meta/packages'
import { readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { gzipSync } from 'node:zlib'
import { globSync } from 'tinyglobby'
import { packages } from '../meta/packages'
import { readJSON, root } from './utils'

interface SizeEntry {
  /** Path relative to the repo root, e.g. `packages/core/dist/index.js`. */
  file: string
  /** Entry name from the file stem, e.g. `index` or `useDrauu`. */
  name: string
  raw: number
  gzip: number
}

interface BuiltPackage {
  pkg: PackageManifest
  /** The package's ESM barrel (`dist/index.js`). */
  barrel: SizeEntry
  /** Per-hook entries (`dist/<hook>.js`), empty unless the package ships submodules. */
  hooks: SizeEntry[]
}

const PAGE = 'packages/export-size.md'
const SCRIPT_URL = 'https://github.com/hairyf/reause/blob/main/scripts/export-size.ts'
const ENTRY_RE = /\.(?:js|mjs)$/

/**
 * Measure every ESM entry of one package's `dist`. IIFE builds are skipped:
 * they bundle React for a `<script>` tag and are ~2× the ESM entry, so they
 * would double-count. Requires `npm run build` to have run first.
 */
function measureEntries(pkg: string): SizeEntry[] {
  return globSync(`packages/${pkg}/dist/*.{js,mjs}`, { cwd: root })
    .filter(file => !file.includes('.iife.'))
    .map((file) => {
      const full = join(root, file)
      return {
        file,
        name: file.slice(file.lastIndexOf('/') + 1).replace(ENTRY_RE, ''),
        raw: statSync(full).size,
        gzip: gzipSync(readFileSync(full)).length,
      }
    })
}

/** Largest first, name as the tie-break so repeated runs are byte-identical. */
function byGzip(a: SizeEntry, b: SizeEntry): number {
  return b.gzip - a.gzip || a.name.localeCompare(b.name)
}

function formatSize(bytes: number): string {
  return `${(bytes / 1000).toFixed(2)} kB`
}

/** Markdown table in the shape `eslint --fix` (prettier) keeps: padded, left-aligned. */
function markdownTable(rows: string[][]): string {
  const widths = rows[0].map((_, column) => Math.max(...rows.map(row => row[column].length)))
  function line(cells: string[]): string {
    return `| ${cells.map((cell, column) => cell.padEnd(widths[column])).join(' | ')} |`
  }
  return [
    line(rows[0]),
    `| ${widths.map(width => '-'.repeat(width)).join(' | ')} |`,
    ...rows.slice(1).map(line),
  ].join('\n')
}

/**
 * Report bundle sizes of the built packages and write `packages/export-size.md`,
 * the page whose header claims to be generated by `npm run size`.
 *
 * Mirrors VueUse's `scripts/export-size.ts` in intent only: upstream measures
 * tree-shaken per-export bundles with rollup via the `export-size` package,
 * which cannot resolve React's CJS-only `react/jsx-runtime` named export (see
 * `.github/workflows/export-size.yml`). Here every figure is the gzip size of a
 * built entry file instead — a different, coarser convention that the page states.
 */
export function exportSize() {
  const { version } = readJSON('package.json') as { version: string }

  const built: BuiltPackage[] = []
  const unbuilt: string[] = []

  for (const pkg of packages) {
    const entries = measureEntries(pkg.name)
    const barrel = entries.find(entry => entry.name === 'index')
    if (!barrel) {
      unbuilt.push(pkg.display)
      continue
    }
    built.push({
      pkg,
      barrel,
      // A package whose `dist` holds more than one ESM entry ships one entry
      // per hook (`tsdown` submodules); its barrel only re-exports.
      hooks: entries.length > 1 ? entries.filter(entry => entry.name !== 'index').sort(byGzip) : [],
    })
  }

  // Never emit a partial page: a package without dist means the build is missing.
  if (unbuilt.length > 0) {
    console.warn('[size] no dist output found — run `npm run build` first')
    console.warn(`[size] missing: ${unbuilt.join(', ')}`)
    return
  }

  const bySize = [...built].sort((a, b) => byGzip(a.barrel, b.barrel))

  console.log(`\n${'file'.padEnd(48)}${'raw'.padStart(10)}${'gzip'.padStart(10)}`)
  for (const { barrel, hooks } of bySize) {
    for (const entry of [barrel, ...hooks]) {
      console.log(
        `${entry.file.padEnd(48)}${String(entry.raw).padStart(10)}${String(entry.gzip).padStart(10)}`,
      )
    }
  }
  console.log()

  const md: string[] = [
    '# Export size\n',
    `version: ${version}<br>`,
    `measured: ${new Date().toISOString().slice(0, 10)}<br>`,
    `generated by [\`npm run size\`](${SCRIPT_URL}) (run \`npm run build\` first)\n`,
    '> Each figure is the gzip size of a **built entry file** (`min+gzipped`), not a tree-shaken per-export bundle: importing two functions does not mean their entries sum, and the real result depends on your bundler and minifier — treat this list as a reference only.\n',
    'Per-package ESM bundles (`dist/index.js`, min+gzipped):\n',
    markdownTable([
      ['Package', 'min+gzipped'],
      ...bySize.map(({ pkg, barrel }) => [`\`${pkg.display}\``, formatSize(barrel.gzip)]),
    ]),
    '',
  ]

  const submodules = bySize.filter(({ hooks }) => hooks.length > 0)
  if (submodules.length > 0) {
    const names = submodules.map(({ pkg }) => `\`${pkg.display}\``)
    const list = names.length > 1 ? `${names.slice(0, -1).join(', ')} and ${names.at(-1)}` : names[0]
    md.push(
      `${list} publish one entry per hook, so their barrels only re-export; the per-hook entries are the sizes that matter:\n`,
    )
    for (const { pkg, hooks } of submodules) {
      md.push(`<kbd>${pkg.display}</kbd>\n`)
      md.push(markdownTable([
        ['Function', 'min+gzipped'],
        ...hooks.map(entry => [`\`${entry.name}\``, formatSize(entry.gzip)]),
      ]))
      md.push('')
    }
  }

  const content = `${md.join('\n').replace(/\r\n/g, '\n').trimEnd()}\n`
  writeFileSync(join(root, PAGE), content, 'utf-8')
  console.log(`[size] wrote ${PAGE}`)
}

if (process.argv[1]?.endsWith('export-size.ts'))
  exportSize()
