import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { format } from 'prettier'
import { globSync } from 'tinyglobby'
import { root } from './utils'

/**
 * Unify every hook docs page (`packages/<pkg>/<Fn>/index.md`) onto VueUse's
 * minimal layout:
 *
 *   ---
 *   category: <Category>
 *   ---
 *   # useXxx
 *   Short one-line description.
 *   [::: note blocks]
 *   [populated at build time: ## Demo + DemoContainer — demo on top]
 *   ## Usage
 *   concise usage code + meaningful subsections
 *   [populated at build time: ## Type Declarations + ## Source + Contributors]
 *
 * Removes the hand-written bloat (long `**Mapping:**` / `**React divergences:**`
 * paragraphs, copied `## Type Declarations`, hand-rolled `## Source` sections)
 * — those are auto-generated by `packages/.vitepress/plugins/markdownTransform.ts`
 * at build time, mirroring VueUse.
 *
 * Side output: `packages/metadata/src/upstream.ts`, mapping each page to its
 * upstream VueUse module path (extracted from the old hand-written Source
 * sections, which carried the correctly-renamed upstream names per AGENTS.md).
 *
 * Usage: `pnpm tsx scripts/unify-demo-layout.ts`
 */

interface Page { pkg: string, dir: string, file: string, raw: string }

const PAGE_GLOB = join(root, 'packages', '{core,shared,math,integrations,electron,firebase,rxjs}', '*', 'index.md')

function collectPages(): Page[] {
  return globSync(PAGE_GLOB.replace(/\\/g, '/')).map((file) => {
    const [, pkg, dir] = file.match(/packages\/(\w+)\/(\w+)\/index\.md$/) || []
    return { pkg, dir, file, raw: readFileSync(file, 'utf-8') }
  }).filter(p => p.pkg && p.dir)
}

/** Frontmatter block (with surrounding `---` lines), or '' when absent. */
function extractFrontmatter(raw: string): { fm: string, rest: string } {
  const m = raw.match(/^---\n[\s\S]*?\n---\n?/)
  if (!m)
    return { fm: '', rest: raw }
  return { fm: m[0], rest: raw.slice(m[0].length) }
}

/** One-line description: first paragraph, single line, port-tail stripped. */
function oneLineDescription(firstParagraph: string): string {
  const joined = firstParagraph.replace(/\s+/g, ' ').trim()
  const cut = /[—–\-]\s*React port of VueUse's/.exec(joined)
  return (cut ? joined.slice(0, cut.index) : joined).trim()
}

/**
 * Chunk the body into blank-line-separated paragraphs and drop the verbose
 * mapping / divergence notes (the "unnecessary information"). A `**React
 * divergences:**` marker is followed by a bullet list in its own paragraph —
 * that continuation is dropped too.
 */
function dropMappingNotes(rest: string): string {
  const chunks = rest.split(/\n\s*\n/)
  const out: string[] = []
  let prevDiscarded = false
  for (const chunk of chunks) {
    if (/^\s*\*\*(?:Mapping|React divergences)\*\*/.test(chunk)) {
      prevDiscarded = true
      continue
    }
    const isBulletChunk = (c: string) => c.trim().split('\n').every(line => /^\s*[-*]\s+\S/.test(line))
    if (prevDiscarded && isBulletChunk(chunk)) {
      prevDiscarded = true
      continue
    }
    prevDiscarded = false
    out.push(chunk)
  }
  return out.join('\n\n')
}

/** Remove whole `## <Section>` blocks (Type Declarations, Source, ...). */
const DROPPED_SECTIONS = ['Type Declarations', 'Source', 'Mapping', 'React divergences']
function dropSections(text: string): string {
  const lines = text.split('\n')
  const out: string[] = []
  let skip = false
  for (const line of lines) {
    const h = line.match(/^## (.+)$/)?.[1]?.trim()
    if (h) {
      skip = DROPPED_SECTIONS.includes(h)
      if (skip)
        continue
    }
    if (!skip)
      out.push(line)
  }
  return out.join('\n')
}

function normalizeLinks(text: string): string {
  // Hand-written page links should match the site's canonical trailing-slash
  // routes (`/core/useStorage/`), not the `/core/useStorage/index` variant.
  return text.replace(/(\]\(\/(?:core|shared|math|integrations)\/\w+)\/index(\))/g, '$1$2')
}

/** VueUse upstream implementation URL present in the old Source section. */
export function upstreamPath(page: Page): string | undefined {
  const urls = [...page.raw.matchAll(/https:\/\/github\.com\/vueuse\/vueuse\/blob\/main\/(packages\/[^\s)]+)/g)]
    .map(m => m[1])
  return urls.find(u => u.endsWith('index.ts')) ?? urls[0]
}

/**
 * Same extraction, from the committed page (HEAD) — the working tree has no
 * `Source` sections anymore once the rewrite has run.
 */
export function headUpstreamPath(page: Page): string | undefined {
  try {
    const blob = execSync(`git show HEAD:packages/${page.pkg}/${page.dir}/index.md`, { cwd: root, encoding: 'utf-8' })
    const urls = [...blob.matchAll(/https:\/\/github\.com\/vueuse\/vueuse\/blob\/main\/(packages\/[^\s)]+)/g)]
      .map(m => m[1])
    return urls.find(u => u.endsWith('index.ts')) ?? urls[0]
  }
  catch {
    return undefined
  }
}

export /**
        * Split the intro region (below `# H1`) into paragraphs and `::: note` blocks,
        * tracking fenced code and note blocks line-by-line so internal blank lines
        * don't break them apart.
        */
function splitIntro(intro: string): { prose: string[], notes: string[] } {
  const prose: string[] = []
  const notes: string[] = []
  let para: string[] = []
  let note: string[] | null = null
  let fence = false
  const flushPara = () => {
    if (para.join('\n').trim())
      prose.push(para.join('\n').trim())
    para = []
  }
  for (const line of intro.split('\n')) {
    const t = line.trim()
    if (note) {
      note.push(line)
      if (/^:{3,}$/.test(t)) {
        notes.push(note.join('\n').trim())
        note = null
      }
      continue
    }
    if (fence) {
      para.push(line)
      if (t.startsWith('```'))
        fence = false
      continue
    }
    if (t.startsWith('```')) {
      flushPara()
      fence = true
      para.push(line)
    }
    else if (/^:{3,}/.test(t)) {
      flushPara()
      note = [line]
    }
    else if (t === '') {
      flushPara()
    }
    else {
      para.push(line)
    }
  }
  flushPara()
  return { prose, notes }
}

export function transform(page: Page): string {
  const { fm, rest: afterFm } = extractFrontmatter(page.raw)

  // 1. structural removals (mapping notes, copied sections, component lines)
  let body = dropMappingNotes(afterFm)
  body = dropSections(body)
  body = body
    .split('\n')
    .filter(line => !/^\s*<DemoContainer\b/.test(line) && !/^\s*<Contributors\b/.test(line))
    .join('\n')
  body = normalizeLinks(body)
  body = body.replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim()

  // 2. split intro (H1 + description/notes) from the first `## `-led body
  const h2 = body.search(/^#{2,6} /m)
  const intro = h2 === -1 ? body : body.slice(0, h2).trim()
  const section = h2 === -1 ? '' : body.slice(h2).trim()

  // 3. intro: `# Name` + one-line description + keep ::: notes
  const h1 = intro.match(/^# ([^\n]+)/)?.[1] ?? page.dir
  const afterH1 = intro.replace(/^# [^\n]+/, '').trim()
  const { prose, notes } = splitIntro(afterH1)
  const description = prose.length ? oneLineDescription(prose[0]) : ''

  const out: string[] = []
  out.push(fm.trimEnd(), '')
  out.push(`# ${h1}`, '')
  if (description)
    out.push(description, '')
  for (const note of notes)
    out.push(note, '')
  if (section)
    out.push(section, '')

  return `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`
}

async function main() {
  const pages = collectPages()
  let changed = 0
  let noDemo = 0
  const upstream: Record<string, string> = {}

  for (const page of pages) {
    const next = transform(page)
    if (next !== page.raw) {
      writeFileSync(page.file, next, 'utf-8')
      changed++
    }
    if (!/<\/?DemoContainer/.test(page.raw))
      noDemo++
    const up = upstreamPath(page) ?? headUpstreamPath(page)
    if (up)
      upstream[`${page.pkg}/${page.dir}`] = up
  }

  const ts = `/**\n * Upstream VueUse module paths — auto-generated by \`scripts/unify-demo-layout.ts\`.\n * Do not edit by hand. Maps a docs page (pkg/module) to its VueUse source\n * path in the \`vueuse/vueuse\` repo, used for the auto-generated\n * \`## Source\` links on function pages.\n */\nexport const upstreamPaths: Record<string, string> = ${JSON.stringify(upstream, null, 2)}\n`
  writeFileSync(join(root, 'packages/metadata/src/upstream.ts'), await format(ts, { parser: 'typescript', singleQuote: true, semi: false, trailingComma: 'all', printWidth: 120 }))

  console.log(`[unify] ${changed}/${pages.length} pages rewritten`)
  console.log(`[unify] pages without DemoContainer in source: ${noDemo}`)
  console.log(`[unify] upstream mappings: ${Object.keys(upstream).length}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
