import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { format } from 'prettier'
import { globSync } from 'tinyglobby'
import { root } from './utils'

interface MappedFunction {
  name: string
  file: string
  pkg: string
  /** Docs-page directory (`packages/<pkg>/<page>`), shared by every export of that page. */
  dir: string
  /** Docs-page category, read from the co-located index.md frontmatter. */
  category: string
  /** Last commit unix-ms touching the hook source file (for `sort=updated`). */
  lastUpdated?: number
}

/**
 * Page-level view of the registry — the reaxuse analogue of VueUse's
 * `metadata.functions`, which is keyed by function *directory*
 * (`packages/<package>/<name>/`) rather than by exported symbol. Every
 * export of a page (`useBreakpoints` + `breakpointsTailwind` + …) collapses
 * onto a single entry here, which is what the generated agent skill
 * (`packages/skills/build.ts`) consumes.
 */
interface MappedPage {
  name: string
  pkg: string
  /** Docs page, relative to the repo root (`packages/<pkg>/<page>/index.md`). */
  doc: string
  category: string
  description: string
  /** Not part of the public surface — mirrors VueUse's `listFunctions` `_*` ignore. */
  internal?: boolean
  lastUpdated?: number
}

const RE_EXPORT = /export\s+(?:async\s+)?function\s+(\w+)|export\s+const\s+(\w+)\s*=/g

function parseExports(file: string): string[] {
  const content = readFileSync(file, 'utf-8')
  const names: string[] = []
  for (const match of content.matchAll(RE_EXPORT)) {
    names.push(match[1] || match[2])
  }
  return names
}

/**
 * Last commit time (ms) of a hook source file, via `git log -1 --format=%at`.
 * Mirrors VueUse's `git.raw(['log', '-1', '--format=%at', tsPath]) * 1000`
 * (metadata/scripts/update.ts). Returns `undefined` when the file is not
 * tracked (or git fails) so callers can fall back gracefully.
 */
function getLastUpdated(file: string): number | undefined {
  try {
    const at = execSync(`git log -1 --format=%at -- "${file}"`, { cwd: root, encoding: 'utf-8' }).trim()
    const seconds = Number(at)
    return Number.isFinite(seconds) && seconds > 0 ? seconds * 1000 : undefined
  }
  catch {
    return undefined
  }
}

/**
 * Scan every hook package's co-located modules (`packages/<pkg>/<hook>/index.tsx`)
 * and regenerate `meta/functions.md` and `meta/functions.ts` (the structured
 * registry consumed by the docs markdown transformer and the PWA route list),
 * mirroring VueUse's metadata-driven function list.
 */
export async function generateFunctionsMD() {
  const functions = collectFunctions()

  functions.sort((a, b) => a.name.localeCompare(b.name))

  const rows = functions.map((fn) => {
    const upstream = `source/vueuse/packages/${fn.pkg}/${fn.name}`
    const upstreamExists = globSync(`${upstream}/index.ts`, { cwd: root }).length > 0
    const upstreamRef = upstreamExists ? `packages/${fn.pkg}/${fn.name}` : '—'
    const status = upstreamExists ? '✅ ported' : '🚧 ported (no upstream match)'
    return `| \`${fn.name}\` | ${upstreamRef} | \`${fn.file}\` | ${status} |`
  })

  const md = `# Function mapping status

> Auto-generated by \`npm run update\` (scripts/update.ts) — do not edit by hand.
> The upstream source of truth is the \`source/vueuse\` submodule.

| VueUse function | source (vueuse) | reaxuse | status |
|---|---|---|---|
${rows.join('\n') || '| — | — | — | no hooks mapped yet |'}
`

  writeFileSync(join(root, 'meta/functions.md'), await format(md, { parser: 'markdown' }))
  console.log(`[update] wrote meta/functions.md (${functions.length} functions)`)
}

function collectFunctions(): MappedFunction[] {
  // hooks live co-located with their docs: packages/<pkg>/<hook>/index.tsx
  // (metadata is not scanned — its files are generated, not hooks)
  const files = globSync('packages/{core,shared,math,integrations,electron,firebase,rxjs}/*/index.tsx', {
    cwd: root,
    absolute: true,
  })

  const functions: MappedFunction[] = []
  const seen = new Set<string>()
  for (const file of files) {
    const rel = file.replace(/\\/g, '/')
    const [, pkg, dir] = rel.match(/packages\/(\w+)\/([^/]+)\/index\.tsx$/) || []
    if (!pkg || !dir)
      continue
    const category = getPageCategory(pkg, dir)
    const lastUpdated = getLastUpdated(`packages/${pkg}/${dir}/index.tsx`)
    for (const name of parseExports(file)) {
      // TypeScript overload signatures export the same name repeatedly —
      // collapse them into a single registry entry per (name, file).
      const key = `${name}\u0000${pkg}/${dir}`
      if (seen.has(key))
        continue
      seen.add(key)
      functions.push({ name, file: `packages/${pkg}/${dir}/index.tsx`, pkg, dir, category, lastUpdated })
    }
  }
  return functions.sort((a, b) => a.name.localeCompare(b.name))
}

/**
 * Collapse the export-level registry onto docs pages — one entry per
 * `packages/<pkg>/<page>/index.md`, named after the page directory exactly
 * like VueUse's directory-driven metadata (`useBreakpoints` covers
 * `breakpointsTailwind` & co.). Consumed by `packages/skills/build.ts`, which
 * mirrors VueUse's `packages/skills/build.ts` one function page per skill
 * reference.
 */
function collectPages(functions: MappedFunction[]): MappedPage[] {
  const byDir = new Map<string, MappedFunction[]>()
  for (const fn of functions) {
    const key = `${fn.pkg}/${fn.dir}`
    const list = byDir.get(key)
    if (list)
      list.push(fn)
    else
      byDir.set(key, [fn])
  }

  const pages: MappedPage[] = []
  for (const entries of byDir.values()) {
    const { pkg, dir, category, lastUpdated } = entries[0]
    const md = readFileSync(join(root, 'packages', pkg, dir, 'index.md'), 'utf-8')
    pages.push({
      name: dir,
      pkg,
      doc: `packages/${pkg}/${dir}/index.md`,
      category,
      description: extractDescription(md),
      // `_`-prefixed directories are shared internals rather than a documented
      // composable — VueUse's `listFunctions` skips them the same way.
      internal: dir.startsWith('_') || undefined,
      lastUpdated: lastUpdated ? Math.max(...entries.map(e => e.lastUpdated || 0)) : undefined,
    })
  }

  return pages.sort((a, b) => a.name.localeCompare(b.name))
}

/**
 * Intro sentence of a docs page, used as the skill-table description.
 * Ports VueUse's `readMetadata()` (packages/metadata/scripts/update.ts):
 * drop the frontmatter and `:::` container blocks, take the first paragraph
 * after the `#` heading, then lower-case the leading character unless the
 * description starts with an abbreviation.
 */
function extractDescription(md: string): string {
  const content = md.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '')
  const matched = (
    content
      // normalize newlines
      .replace(/\r\n/g, '\n')
      // remove ::: tip blocks
      .replace(/(:{3,}(?=[^:\n]*\n))[^\n]*\n[\s\S]*?\1 *(?=\n)/g, '')
      // remove headers
      .match(/#(?=\s).*\n+(.+?)(?:, |\. |\n|\.\n)/) || []
  )[1] || ''

  const description = matched.trim()
  if (!/^[A-Z][A-Z]/.test(description))
    return description.charAt(0).toLowerCase() + description.slice(1)
  return description
}

/**
 * Write `packages/metadata/src/functions.ts` — the structured function
 * registry (name/pkg/file/category/lastUpdated) consumed by the docs
 * markdown transformer, the PWA route list and the theme's FunctionsList
 * (category filter / search / sort), plus the page-level `pages` view the
 * agent-skill generator consumes. Mirrors VueUse's generated
 * `packages/metadata/metadata.ts`.
 */
async function generateFunctionsTS() {
  // The /functions registry drives sidebar-visible docs pages: keep only
  // functions whose co-located page (index.md) exists, so every entry in
  // the FunctionsList links to a real page (mirrors VueUse's page-driven
  // metadata; the progress table in meta/functions.md keeps all entries).
  const functions = collectFunctions().filter((fn) => {
    const [, pkg, dir] = fn.file.match(/^packages\/(\w+)\/([^/]+)\/index\.tsx$/) || []
    if (!pkg || !dir)
      return false
    try {
      readFileSync(join(root, 'packages', pkg, dir, 'index.md'))
      return true
    }
    catch {
      return false
    }
  })

  const pages = collectPages(functions)

  // Category list in VueUse's canonical order: core categories first,
  // `@`-prefixed addon categories last (mirrors `categoryNames` in
  // vueuse/packages/metadata/metadata.ts).
  const categoryNames = [...new Set(functions.map(fn => fn.category))]
    .sort((a, b) => rankCategory(a) - rankCategory(b) || a.localeCompare(b))

  const ts = `/* eslint-disable style/quotes -- prettier keeps double quotes around descriptions containing an apostrophe */
/**
 * Function registry — auto-generated by \`npm run update\` (scripts/update.ts).
 * Do not edit by hand. Mirrors VueUse's generated
 * \`packages/metadata/metadata.ts\` (react-adapted).
 */
export interface FunctionInfo {
  name: string
  pkg: string
  /** Page directory the export belongs to (\`packages/<pkg>/<dir>\`). */
  dir: string
  file: string
  category: string
  lastUpdated?: number
}

/**
 * Page-level registry: one entry per \`packages/<pkg>/<page>/index.md\`, named
 * after the page directory like VueUse's directory-driven metadata. Consumed
 * by \`packages/skills/build.ts\`.
 */
export interface FunctionPageInfo {
  name: string
  pkg: string
  doc: string
  category: string
  description: string
  internal?: boolean
  lastUpdated?: number
}

export const functions: FunctionInfo[] = ${JSON.stringify(functions, null, 2)}

export const pages: FunctionPageInfo[] = ${JSON.stringify(pages, null, 2)}

export const categoryNames: string[] = ${JSON.stringify(categoryNames, null, 2)}

export const coreCategoryNames = categoryNames.filter(c => !c.startsWith('@'))

export const addonCategoryNames = categoryNames.filter(c => c.startsWith('@'))
`
  writeFileSync(join(root, 'packages/metadata/src/functions.ts'), await format(ts, { parser: 'typescript', singleQuote: true, semi: false, trailingComma: 'all', printWidth: 120, arrowParens: 'avoid' }))
  console.log(`[update] wrote packages/metadata/src/functions.ts (${functions.length} functions, ${pages.length} pages, ${categoryNames.length} categories)`)
}

// Category order mirrors VueUse's `packages/metadata/metadata.ts`
// `categoriesOrder` (addon categories, prefixed with `@`, sort after core).
const CATEGORY_ORDER = [
  'State',
  'Elements',
  'Browser',
  'Sensors',
  'Network',
  'Animation',
  'Component',
  'Watch',
  'Reactivity',
  'Array',
  'Time',
  'Utilities',
]

// Read the docs-page category from the co-located index.md frontmatter
// (packages/<pkg>/<page>/index.md). Returns 'Uncategorized' when the page
// has none or doesn't exist.
function getPageCategory(pkg: string, page: string): string {
  try {
    return readFileSync(join(root, 'packages', pkg, page, 'index.md'), 'utf-8')
      .split('\n')
      .find(line => line.startsWith('category:'))
      ?.slice('category:'.length)
      .trim()
      .replace(/^['"]|['"]$/g, '') || 'Uncategorized'
  }
  catch {
    return 'Uncategorized'
  }
}

// VueUse's canonical category order: known core categories by rank, unknown
// categories after, `@`-prefixed addon categories last.
function rankCategory(c: string): number {
  const i = CATEGORY_ORDER.indexOf(c)
  if (i !== -1)
    return i
  return c.startsWith('@') ? CATEGORY_ORDER.length : CATEGORY_ORDER.length + 1
}

/**
 * Regenerate `packages/functions.md` — the /functions/ docs page.
 * Mirrors VueUse's auto-generated `packages/functions.md`: a thin page that
 * renders the theme's `<FunctionsList />` component (category filter, search
 * and sort driven by `#category=` / `#search=` / `#sort=` hash params, e.g.
 * `/functions#category=State` from the sidebar/nav category links).
 */
async function generateFunctionsPage() {
  const md = `# Functions

<FunctionsList />
`
  writeFileSync(join(root, 'packages/functions.md'), await format(md, { parser: 'markdown' }))
  console.log('[update] wrote packages/functions.md (<FunctionsList />)')
}

async function main() {
  await generateFunctionsMD()
  await generateFunctionsTS()
  await generateFunctionsPage()
}

main()
