import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { format } from 'prettier'
import { globSync } from 'tinyglobby'
import { root } from './utils'

interface MappedFunction {
  name: string
  file: string
  pkg: string
  /** Docs-page category, read from the co-located index.md frontmatter. */
  category: string
  /** Last commit unix-ms touching the hook source file (for `sort=updated`). */
  lastUpdated?: number
}

const RE_EXPORT = /export\s+(?:async\s+)?function\s+(\w+)|export\s+const\s+(\w+)\s*=/g

function parseExports(file: string): string[] {
  const content = readFileSync(file, 'utf-8')
  const names: string[] = []
  for (const match of content.matchAll(RE_EXPORT)) {
    names.push(match[1] || match[2])
  }
  return names
}

/**
 * Last commit time (ms) of a hook source file, via `git log -1 --format=%at`.
 * Mirrors VueUse's `git.raw(['log', '-1', '--format=%at', tsPath]) * 1000`
 * (metadata/scripts/update.ts). Returns `undefined` when the file is not
 * tracked (or git fails) so callers can fall back gracefully.
 */
function getLastUpdated(file: string): number | undefined {
  try {
    const at = execSync(`git log -1 --format=%at -- "${file}"`, { cwd: root, encoding: 'utf-8' }).trim()
    const seconds = Number(at)
    return Number.isFinite(seconds) && seconds > 0 ? seconds * 1000 : undefined
  }
  catch {
    return undefined
  }
}

/**
 * Scan every hook package's co-located modules (`packages/<pkg>/<hook>/index.tsx`)
 * and regenerate `meta/functions.md` and `meta/functions.ts` (the structured
 * registry consumed by the docs markdown transformer and the PWA route list),
 * mirroring VueUse's metadata-driven function list.
 */
export async function generateFunctionsMD() {
  const functions = collectFunctions()

  functions.sort((a, b) => a.name.localeCompare(b.name))

  const rows = functions.map((fn) => {
    const upstream = `source/vueuse/packages/${fn.pkg}/${fn.name}`
    const upstreamExists = globSync(`${upstream}/index.ts`, { cwd: root }).length > 0
    const upstreamRef = upstreamExists ? `packages/${fn.pkg}/${fn.name}` : '—'
    const status = upstreamExists ? '✅ ported' : '🚧 ported (no upstream match)'
    return `| \`${fn.name}\` | ${upstreamRef} | \`${fn.file}\` | ${status} |`
  })

  const md = `# Function mapping status

> Auto-generated by \`npm run update\` (scripts/update.ts) — do not edit by hand.
> The upstream source of truth is the \`source/vueuse\` submodule.

| VueUse function | source (vueuse) | reaxuse | status |
|---|---|---|---|
${rows.join('\n') || '| — | — | — | no hooks mapped yet |'}
`

  writeFileSync(join(root, 'meta/functions.md'), await format(md, { parser: 'markdown' }))
  console.log(`[update] wrote meta/functions.md (${functions.length} functions)`)
}

function collectFunctions(): MappedFunction[] {
  // hooks live co-located with their docs: packages/<pkg>/<hook>/index.tsx
  // (metadata is not scanned — its files are generated, not hooks)
  const files = globSync('packages/{core,shared,math,integrations,electron,firebase,rxjs}/*/index.tsx', {
    cwd: root,
    absolute: true,
  })

  const functions: MappedFunction[] = []
  const seen = new Set<string>()
  for (const file of files) {
    const rel = file.replace(/\\/g, '/')
    const [, pkg, dir] = rel.match(/packages\/(\w+)\/([^/]+)\/index\.tsx$/) || []
    if (!pkg || !dir)
      continue
    const category = getPageCategory(pkg, dir)
    const lastUpdated = getLastUpdated(`packages/${pkg}/${dir}/index.tsx`)
    for (const name of parseExports(file)) {
      // TypeScript overload signatures export the same name repeatedly —
      // collapse them into a single registry entry per (name, file).
      const key = `${name}\u0000${pkg}/${dir}`
      if (seen.has(key))
        continue
      seen.add(key)
      functions.push({ name, file: `packages/${pkg}/${dir}/index.tsx`, pkg, category, lastUpdated })
    }
  }
  return functions.sort((a, b) => a.name.localeCompare(b.name))
}

/**
 * Write `packages/metadata/src/functions.ts` — the structured function
 * registry (name/pkg/file/category/lastUpdated) consumed by the docs
 * markdown transformer, the PWA route list and the theme's FunctionsList
 * (category filter / search / sort). Mirrors VueUse's generated
 * `packages/metadata/metadata.ts`.
 */
async function generateFunctionsTS() {
  // The /functions registry drives sidebar-visible docs pages: keep only
  // functions whose co-located page (index.md) exists, so every entry in
  // the FunctionsList links to a real page (mirrors VueUse's page-driven
  // metadata; the progress table in meta/functions.md keeps all entries).
  const functions = collectFunctions().filter((fn) => {
    const [, pkg, dir] = fn.file.match(/^packages\/(\w+)\/([^/]+)\/index\.tsx$/) || []
    if (!pkg || !dir)
      return false
    try {
      readFileSync(join(root, 'packages', pkg, dir, 'index.md'))
      return true
    }
    catch {
      return false
    }
  })

  // Category list in VueUse's canonical order: core categories first,
  // `@`-prefixed addon categories last (mirrors `categoryNames` in
  // vueuse/packages/metadata/metadata.ts).
  const categoryNames = [...new Set(functions.map(fn => fn.category))]
    .sort((a, b) => rankCategory(a) - rankCategory(b) || a.localeCompare(b))

  const ts = `/**
 * Function registry — auto-generated by \`npm run update\` (scripts/update.ts).
 * Do not edit by hand. Mirrors VueUse's generated
 * \`packages/metadata/metadata.ts\` (react-adapted).
 */
export interface FunctionInfo {
  name: string
  pkg: string
  file: string
  category: string
  lastUpdated?: number
}

export const functions: FunctionInfo[] = ${JSON.stringify(functions, null, 2)}

export const categoryNames: string[] = ${JSON.stringify(categoryNames, null, 2)}

export const coreCategoryNames = categoryNames.filter(c => !c.startsWith('@'))

export const addonCategoryNames = categoryNames.filter(c => c.startsWith('@'))
`
  writeFileSync(join(root, 'packages/metadata/src/functions.ts'), await format(ts, { parser: 'typescript', singleQuote: true, semi: false, trailingComma: 'all', printWidth: 120 }))
  console.log(`[update] wrote packages/metadata/src/functions.ts (${functions.length} functions, ${categoryNames.length} categories)`)
}

// Category order mirrors VueUse's `packages/metadata/metadata.ts`
// `categoriesOrder` (addon categories, prefixed with `@`, sort after core).
const CATEGORY_ORDER = [
  'State',
  'Elements',
  'Browser',
  'Sensors',
  'Network',
  'Animation',
  'Component',
  'Watch',
  'Reactivity',
  'Array',
  'Time',
  'Utilities',
]

// Read the docs-page category from the co-located index.md frontmatter
// (packages/<pkg>/<page>/index.md). Returns 'Uncategorized' when the page
// has none or doesn't exist.
function getPageCategory(pkg: string, page: string): string {
  try {
    return readFileSync(join(root, 'packages', pkg, page, 'index.md'), 'utf-8')
      .split('\n')
      .find(line => line.startsWith('category:'))
      ?.slice('category:'.length)
      .trim()
      .replace(/^['"]|['"]$/g, '') || 'Uncategorized'
  }
  catch {
    return 'Uncategorized'
  }
}

// VueUse's canonical category order: known core categories by rank, unknown
// categories after, `@`-prefixed addon categories last.
function rankCategory(c: string): number {
  const i = CATEGORY_ORDER.indexOf(c)
  if (i !== -1)
    return i
  return c.startsWith('@') ? CATEGORY_ORDER.length : CATEGORY_ORDER.length + 1
}

/**
 * Regenerate `packages/functions.md` — the /functions/ docs page.
 * Mirrors VueUse's auto-generated `packages/functions.md`: a thin page that
 * renders the theme's `<FunctionsList />` component (category filter, search
 * and sort driven by `#category=` / `#search=` / `#sort=` hash params, e.g.
 * `/functions#category=State` from the sidebar/nav category links).
 */
async function generateFunctionsPage() {
  const md = `# Functions

<FunctionsList />
`
  writeFileSync(join(root, 'packages/functions.md'), await format(md, { parser: 'markdown' }))
  console.log('[update] wrote packages/functions.md (<FunctionsList />)')
}

async function main() {
  await generateFunctionsMD()
  await generateFunctionsTS()
  await generateFunctionsPage()
}

main()
