import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { globSync } from 'tinyglobby'
import { root } from './utils'

interface MappedFunction {
  name: string
  file: string
  pkg: string
}

const RE_EXPORT = /export\s+(?:async\s+)?function\s+(\w+)|export\s+const\s+(\w+)\s*=/g

function parseExports(file: string): string[] {
  const content = readFileSync(file, 'utf-8')
  const names: string[] = []
  for (const match of content.matchAll(RE_EXPORT)) {
    names.push(match[1] || match[2])
  }
  return names
}

/**
 * Scan every package `src` dir and regenerate `meta/functions.md`,
 * mirroring VueUse's metadata-driven function list.
 */
export function generateFunctionsMD() {
  const files = globSync('packages/*/src/*.ts', {
    cwd: root,
    absolute: true,
  }).filter(file => !file.endsWith('index.ts') && !file.includes('.test.'))

  const functions: MappedFunction[] = []
  for (const file of files) {
    const rel = file.replace(/\\/g, '/')
    const [, pkg, basename] = rel.match(/packages\/(\w+)\/src\/(\w+)\.ts$/) || []
    if (!pkg || !basename)
      continue
    for (const name of parseExports(file)) {
      functions.push({ name, file: `packages/${pkg}/src/${basename}.ts`, pkg })
    }
  }

  functions.sort((a, b) => a.name.localeCompare(b.name))

  const rows = functions.map((fn) => {
    const upstream = `source/vueuse/packages/${fn.pkg}/${fn.name}`
    const upstreamExists = globSync(`${upstream}/index.ts`, { cwd: root }).length > 0
    const upstreamRef = upstreamExists ? `packages/${fn.pkg}/${fn.name}` : '—'
    const status = upstreamExists ? '✅ ported' : '🚧 ported (no upstream match)'
    return `| \`${fn.name}\` | ${upstreamRef} | \`${fn.file}\` | ${status} |`
  })

  const md = `# Function mapping status

> Auto-generated by \`npm run update\` (scripts/update.ts) — do not edit by hand.
> The upstream source of truth is the \`source/vueuse\` submodule.

| VueUse function | source (vueuse) | reaxuse | status |
|---|---|---|---|
${rows.join('\n') || '| — | — | — | no hooks mapped yet |'}
`

  writeFileSync(join(root, 'meta/functions.md'), md)
  console.log(`[update] wrote meta/functions.md (${functions.length} functions)`)
}

generateFunctionsMD()
